name: Build & Publish

on: release


jobs:
  Build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux, windows, mac]
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: ''
      run: |
        pip install bumpversion --user
        export regex="([0-9]+.[0-9]+.[0-9]+)"
        echo ${{ github.ref }} > tag.txt
        VERSION=`grep -Po "${regex}" tag.txt`
        bumpversion --new-version ${VERSION}
    - name: Build
      id: build
      uses: josephbmanley/build-godot-action@refactor/build
      with:
        name: glitchinthesystem
        preset: ${{ matrix.platform }}
        subdirectory: gits
    - name: GitHub Release Artifact
      uses: josephbmanley/upload-to-release@feature/remoteName
      with:
        args: ${{ steps.build.outputs.artifact }} application/zip ${{ matrix.platform }}.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Butler Publish
      uses: josephbmanley/butler-publish-itchio-action@v1.0.0
      env:
        BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
        VERSION: develop
        ITCH_USER: joebmanley
        ITCH_GAME: glitchinthesystem
        CHANNEL: ${{ matrix.platform }}
        PACKAGE: ${{ steps.build.outputs.artifact }}
  HTML:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - uses: josephbmanley/auto-semver-action@master
      with:
        args:
          action: updateFiles
          version: ${{ github.ref }}
    - name: Build
      id: build
      uses: josephbmanley/build-godot-action@refactor/build
      with:
        name: glitchinthesystem
        preset: html5
    - name: GitHub Release Artifact
      uses: josephbmanley/upload-to-release@feature/remoteName
      with:
        args: ${{ steps.build.outputs.artifact }} application/zip html5.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Butler Publish
      uses: josephbmanley/butler-publish-itchio-action@v1.0.0
      env:
        BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
        VERSION: develop
        ITCH_USER: joebmanley
        ITCH_GAME: glitchinthesystem
        CHANNEL: html5
        PACKAGE: ${{ steps.build.outputs.artifact }}