name: Build & Push

on: [push]


jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Build Multi-Platform Project
      uses: josephbmanley/build-godot-action@v1.2.1
      env:
        PROJECT: GITS
        SUBDIRECTORY: GITS
    - name: Ship to S3
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --follow-symlinks --delete
      env:
        SOURCE_DIR: build
        AWS_REGION: us-east-1
        DEST_DIR: glitch/builds
        AWS_S3_BUCKET: sumu-games-pkg-us-east-1
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    - name: Butler Publish Linux
      uses: josephbmanley/butler-publish-itchio-action@v1.0.0
      env:
        BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
        VERSION: develop
        ITCH_USER: joebmanley
        ITCH_GAME: glitchinthesystem
        CHANNEL: linux
        PACKAGE: build/linux
    - name: Butler Publish Windows
      uses: josephbmanley/butler-publish-itchio-action@v1.0.0
      env:
        BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
        VERSION: develop
        ITCH_USER: joebmanley
        ITCH_GAME: glitchinthesystem
        CHANNEL: windows
        PACKAGE: build/windows
    - name: Butler Publish HTML5
      uses: josephbmanley/butler-publish-itchio-action@v1.0.0
      env:
        BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
        VERSION: develop
        ITCH_USER: joebmanley
        ITCH_GAME: glitchinthesystem
        CHANNEL: html5
        PACKAGE: build/html5/GITS
    - name: Butler Publish OSX
      uses: josephbmanley/butler-publish-itchio-action@v1.0.0
      env:
        BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
        VERSION: develop
        ITCH_USER: joebmanley
        ITCH_GAME: glitchinthesystem
        CHANNEL: osx
        PACKAGE: build/mac